services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    environment: MYSQL_HOST=147.45.138.192
      MYSQL_USER=gen_user
      MYSQL_PASSWORD=7ezfn-z>xj56nx
      MYSQL_DB=default_db
      APP_URL=http://localhost:8000/api
      APP_SECRET_KEY=4d8ce61245d282d4d4babe5bdb82835e36976223373acd185143a71657b0866e
      APP_ALGORITHM=HS256
      APP_TOKEN_EXPIRE_MINUTES=2000
      STORAGE_BUCKET_NAME=0e67cfac-7b02893a-ce97-4db0-a795-be2a3b9de932
      STORAGE_ENDPOINT_URL=https://s3.timeweb.cloud
      STORAGE_REGION_NAME=ru-1
      STORAGE_KEY_ID=0GHPDV1Q18JDJS54UW9E
      STORAGE_SECRET_KEY=im25WDee7KuselhxrPOfDCiL9uHdl96FhMlDZKkY
    ports:
      - 8000:8000
