"""empty message

Revision ID: 086eca145e30
Revises: f1b2969da11f
Create Date: 2024-04-21 19:55:00.351198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086eca145e30'
down_revision: Union[str, None] = 'f1b2969da11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lands', sa.Column('type_permission_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lands', 'type_permissions', ['type_permission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lands', type_='foreignkey')
    op.drop_column('lands', 'type_permission_id')
    # ### end Alembic commands ###
