"""empty message

Revision ID: 1f04d7d346bd
Revises: 6b5a2652abc3
Create Date: 2024-05-12 15:46:04.176830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f04d7d346bd'
down_revision: Union[str, None] = '6b5a2652abc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighbours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('land_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['land_id'], ['lands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('buildings', sa.Column('neighbor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'buildings', 'materials', ['neighbor_id'], ['id'])
    op.add_column('lands', sa.Column('red_borders', sa.JSON(), nullable=False))
    op.drop_column('lands', 'neighbors_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lands', sa.Column('neighbors_location', mysql.JSON(), nullable=False))
    op.drop_column('lands', 'red_borders')
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.drop_column('buildings', 'neighbor_id')
    op.drop_table('neighbours')
    # ### end Alembic commands ###
