"""empty message

Revision ID: 35bc0d83bd8c
Revises: ff41ae747608
Create Date: 2024-04-23 21:07:08.409132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35bc0d83bd8c'
down_revision: Union[str, None] = 'ff41ae747608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_categories', sa.Column('category_title', sa.String(length=40), nullable=False))
    op.drop_column('land_categories', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_categories', sa.Column('title', mysql.VARCHAR(length=40), nullable=False))
    op.drop_column('land_categories', 'category_title')
    # ### end Alembic commands ###
