"""empty message

Revision ID: 3a53010bd537
Revises: c86b9ca0b1e0
Create Date: 2024-04-25 21:39:03.110806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a53010bd537'
down_revision: Union[str, None] = 'c86b9ca0b1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_permission_buildings')
    op.add_column('init_buildings', sa.Column('type_permission_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'init_buildings', 'type_permissions', ['type_permission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'init_buildings', type_='foreignkey')
    op.drop_column('init_buildings', 'type_permission_id')
    op.create_table('type_permission_buildings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('init_building_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['init_building_id'], ['init_buildings.id'], name='type_permission_buildings_ibfk_1'),
    sa.ForeignKeyConstraint(['type_permission_id'], ['type_permissions.id'], name='type_permission_buildings_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
