"""empty message

Revision ID: 3d528b3a5218
Revises: 91e3ed7bd88c
Create Date: 2024-05-09 12:25:47.526101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d528b3a5218'
down_revision: Union[str, None] = '91e3ed7bd88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_title', sa.String(length=90), nullable=False),
    sa.Column('additional_distance', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_title')
    )
    op.add_column('init_buildings', sa.Column('min_length', sa.SmallInteger(), nullable=False))
    op.add_column('init_buildings', sa.Column('max_length', sa.SmallInteger(), nullable=False))
    op.add_column('init_buildings', sa.Column('min_width', sa.SmallInteger(), nullable=False))
    op.add_column('tips', sa.Column('current_distance', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tips', 'current_distance')
    op.drop_column('init_buildings', 'min_width')
    op.drop_column('init_buildings', 'max_length')
    op.drop_column('init_buildings', 'min_length')
    op.drop_table('materials')
    # ### end Alembic commands ###
