"""empty message

Revision ID: 40aa571b6566
Revises: d700181c414c
Create Date: 2024-06-01 21:22:40.372115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40aa571b6566'
down_revision: Union[str, None] = 'd700181c414c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('norms', 'distance',
               existing_type=mysql.SMALLINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('tips', 'current_distance',
               existing_type=mysql.SMALLINT(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tips', 'current_distance',
               existing_type=sa.Float(),
               type_=mysql.SMALLINT(),
               existing_nullable=False)
    op.alter_column('norms', 'distance',
               existing_type=sa.Float(),
               type_=mysql.SMALLINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
