"""empty message

Revision ID: 4ced61674cc8
Revises: 5978c391a03a
Create Date: 2024-05-10 14:16:50.385495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ced61674cc8'
down_revision: Union[str, None] = '5978c391a03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('norms', sa.Column('type', sa.String(length=30), nullable=False))
    op.add_column('tips', sa.Column('type', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tips', 'type')
    op.drop_column('norms', 'type')
    # ### end Alembic commands ###
