"""empty message

Revision ID: 5978c391a03a
Revises: 3d528b3a5218
Create Date: 2024-05-09 12:30:31.454336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5978c391a03a'
down_revision: Union[str, None] = '3d528b3a5218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('material_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'buildings', 'materials', ['material_id'], ['id'])
    op.drop_column('buildings', 'material')
    op.add_column('init_buildings', sa.Column('max_width', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('init_buildings', 'max_width')
    op.add_column('buildings', sa.Column('material', mysql.VARCHAR(length=40), nullable=False))
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.drop_column('buildings', 'material_id')
    # ### end Alembic commands ###
