"""empty message

Revision ID: 6b5a2652abc3
Revises: 4ced61674cc8
Create Date: 2024-05-11 20:52:34.690908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b5a2652abc3'
down_revision: Union[str, None] = '4ced61674cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'start_x',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('buildings', 'start_y',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'start_y',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('buildings', 'start_x',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
