"""empty message

Revision ID: 7b2cd1b2a778
Revises: 8f7c5eb79b30
Create Date: 2024-05-14 00:06:07.651745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2cd1b2a778'
down_revision: Union[str, None] = '8f7c5eb79b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('buildings_ibfk_3', 'buildings', type_='foreignkey')
    op.create_foreign_key(None, 'buildings', 'neighbours', ['neighbor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.create_foreign_key('buildings_ibfk_3', 'buildings', 'materials', ['neighbor_id'], ['id'])
    # ### end Alembic commands ###
