"""empty message

Revision ID: 840ae439ab66
Revises: b2357b440d7d
Create Date: 2024-05-15 18:50:07.048443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '840ae439ab66'
down_revision: Union[str, None] = 'b2357b440d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'material_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('materials', sa.Column('type', sa.String(length=30), nullable=False))
    op.add_column('materials', sa.Column('color', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'materials', ['type'])
    op.drop_column('materials', 'additional_distance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('additional_distance', mysql.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'materials', type_='unique')
    op.drop_column('materials', 'color')
    op.drop_column('materials', 'type')
    op.alter_column('buildings', 'material_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
