"""empty message

Revision ID: 8f7c5eb79b30
Revises: 1f04d7d346bd
Create Date: 2024-05-12 17:51:16.750606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f7c5eb79b30'
down_revision: Union[str, None] = '1f04d7d346bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neighbours', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint('neighbours_ibfk_1', 'neighbours', type_='foreignkey')
    op.create_foreign_key(None, 'neighbours', 'projects', ['project_id'], ['id'])
    op.drop_column('neighbours', 'land_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neighbours', sa.Column('land_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'neighbours', type_='foreignkey')
    op.create_foreign_key('neighbours_ibfk_1', 'neighbours', 'lands', ['land_id'], ['id'])
    op.drop_column('neighbours', 'project_id')
    # ### end Alembic commands ###
