"""empty message

Revision ID: 91e3ed7bd88c
Revises: e1b3a82c2db6
Create Date: 2024-05-04 13:28:02.451508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e3ed7bd88c'
down_revision: Union[str, None] = 'e1b3a82c2db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'land_categories', ['category_title'])
    op.add_column('norms', sa.Column('priority', sa.String(length=10), nullable=False))
    op.add_column('tips', sa.Column('priority', sa.String(length=10), nullable=False))
    op.add_column('type_permissions', sa.Column('code', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_permissions', 'code')
    op.drop_column('tips', 'priority')
    op.drop_column('norms', 'priority')
    op.drop_constraint(None, 'land_categories', type_='unique')
    # ### end Alembic commands ###
