"""empty message

Revision ID: c86b9ca0b1e0
Revises: 35bc0d83bd8c
Create Date: 2024-04-24 20:40:33.989510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86b9ca0b1e0'
down_revision: Union[str, None] = '35bc0d83bd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('type', table_name='buildings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('type', 'buildings', ['type'], unique=True)
    # ### end Alembic commands ###
