"""empty message

Revision ID: d700181c414c
Revises: 793163d2857e
Create Date: 2024-05-18 10:56:50.991400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd700181c414c'
down_revision: Union[str, None] = '793163d2857e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('type', table_name='init_buildings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('type', 'init_buildings', ['type'], unique=True)
    # ### end Alembic commands ###
