"""empty message

Revision ID: e1b3a82c2db6
Revises: c9c544bf05b7
Create Date: 2024-05-01 12:55:55.510239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b3a82c2db6'
down_revision: Union[str, None] = 'c9c544bf05b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land_categories', sa.Column('image_url', sa.String(length=150), nullable=False))
    op.add_column('type_permissions', sa.Column('image_url', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_permissions', 'image_url')
    op.drop_column('land_categories', 'image_url')
    # ### end Alembic commands ###
